#docker 命令行管理
version: '2.0'
services:    
  mysql:
    container_name: ls_mysql
    image: mysql
    volumes:
      - /var/mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=110
    networks:
      default:
        aliases:
          - mysql_host

  redis:
    container_name: ls_redis
    image: redis:5.0.3-alpine
    volumes:
        - /var/redis_data:/data
    networks:
      default:
        aliases:
          - redis_host
          
  mongo:
    container_name: ls_mongo
    image: mongo:4
    volumes:
        - /var/mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 110
    networks:
      default:
        aliases:
          - mongo_host
        
  php:
    container_name: ls_php
    build:
      context: ./php7
      dockerfile: Dockerfile
    image: shanliu/phpfpm:1
    networks:
      default:
        aliases:
          - php_host
      
  www:
    container_name: ls_www
    image: shanliu/phpfpm:1
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8100:80'
    volumes:
      - $PWD/www:/usr/share/nginx/html:ro #ro 表示只读
      - $PWD/nginx/nginx.conf:/etc/nginx/nginx.conf:ro #配置覆盖
    depends_on:
      - mysql
      - redis
      - mongo
    
