version: '2.0'
services:    
  mysql:
    container_name: ls_mysql
    image: mysql
    volumes:
      - $PWD/docker/data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=110
    networks:
      default:
        aliases:
          - host-mysql

  redis:
    container_name: ls_redis
    image: redis:5.0.3-alpine
    volumes:
        - $PWD/docker/data/redis:/data
    networks:
      default:
        aliases:
          - host-redis
          
  mongo:
    container_name: ls_mongo
    image: mongo:4
    volumes:
        - $PWD/docker/data/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 110
    networks:
      default:
        aliases:
          - host-mongo
        
  php:
    container_name: ls_php
#    build:
#      context: ./docker/php7
#      dockerfile: Dockerfile
    image: shanliu/phpfpm
    volumes:
        - $PWD/docker/php7/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      default:
        aliases:
          - host-php
      
  www:
    container_name: ls_www
    image: shanliu/nginxphp
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8100:80'
    volumes:
      - $PWD/www:/var/www/public_html/:ro #ro 表示只读
      - $PWD/docker/nginx/conf.d/www.conf:/etc/nginx/conf.d/www.conf:ro #配置覆盖
    depends_on:
      - mysql
      - redis
      - mongo
      - php
    
