version: '2.0'
services:    
  mysql:
    container_name: ls_mysql
    image: mysql
    volumes:
      - $PWD/docker/data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=110
    networks:
      default:
        aliases:
          - host-mysql

  redis:
    container_name: ls_redis
    image: redis:5.0.3-alpine
    volumes:
        - $PWD/docker/data/redis:/data
    networks:
      default:
        aliases:
          - host-redis

  php:
    container_name: webdome
    image: shanliu/fpmdome
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - $PWD/www/:/var/www/:ro
      - $PWD/docker/php7/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      default:
        aliases:
          - host-php
    
  nginx:
    container_name: ls_nginx
    image: nginx:1.15.7-alpine
    ports:
      - '8011:80'
    volumes:
      - $PWD/docker/nginx/conf.d/www.conf:/etc/nginx/conf.d/www.conf:ro
      - $PWD/www/public/:/var/www/public/:ro
    depends_on:
      - mysql
      - redis
      - php  
