#docker 命令行管理
version: '2.0'
services:
  phpfpm:
    image: shanliu/phpfpm
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '9000:9000'
    volumes:
      - $PWD/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
    
